<?php
/**
 * ZF3 book Simple Shop Training Application
 *
 * @package    Application
 * @author     Ralf Eggert <ralf@travello.de>
 * @link       https://github.com/zf3buch/simple-shop
 * @license    http://opensource.org/licenses/MIT The MIT License (MIT)
 */
$this->h1('application_h1_index_index');

?>
<div class="well text-center">
    <h3>
        <i class="fa fa-hourglass fa-spin"></i>
        &nbsp;
        <?php echo $this->translate('application_misc_coming_soon') ?>
        &nbsp;
        <i class="fa fa-hourglass fa-spin"></i>
    </h3>
</div>